### ISSUE TITLE
Select cleared when loading with existing value

### ISSUE THREAD

**Issue by alex-osborn** [dillingham/nova-ajax-select#1]
Nice work with the package.

Nova: 1.3.2
dillingham/nova-ajax-select:  1.0.1

When the control is loaded with an initial value (such as on an update form), the initial value is cleared when the options are loaded.

This appears to be happening in the updateOptions() call, where this.value is always set to null. I think a solution would be to only set the value to null if it does not exist in the updated options.

This would have the added benefit of retaining the value if it appears in both the new and old options, currently it is always cleared.

**Comment by dillingham** [comment]
Thanks for catching that and for the detailed bug report.

So instead of setting the value to null on update, I added a check if the value is present in the ajax retrieved options and only set to null if not present. On update views, the option will be there and it will not override the initial value as you describe, but if you change the parent field it and it doesnt have that value.. it will reset the value to null.

Thanks again

**Comment by alex-osborn** [comment]
Awesome, thank you!
